# Generated by Django 3.0.5 on 2020-05-11 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200511_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
