# Generated by Django 3.0.5 on 2020-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200514_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='files_name',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
