# Generated by Django 3.0.5 on 2020-05-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200514_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'Запрос на консультацию', 'verbose_name_plural': 'Запросы на консультации'},
        ),
    ]
