# Generated by Django 3.0.5 on 2020-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200517_1137'),
    ]


