# Generated by Django 3.0.5 on 2020-05-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_query_files_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
    ]
