# Generated by Django 3.0.5 on 2020-05-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200517_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Query status')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_report', models.TextField(verbose_name='Report')),
            ],
        ),
        migrations.DeleteModel(
            name='Medical_record',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='medical_report',
        ),
        migrations.RemoveField(
            model_name='query',
            name='files_name',
        ),
        migrations.AddField(
            model_name='consultation_status',
            name='consultation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Consultation'),
        ),
        migrations.AddField(
            model_name='report',
            name='consultation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Consultation'),
        ),
        migrations.AddField(
            model_name='query_status',
            name='query',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Query'),
        ),
    ]
